# core
- name: "kind/fix"
  color: "d73a4a"
  description: "Fix something isn't working"
- name: "kind/feature"
  color: "a2eeef"
  description: "New feature or request"
- name: "kind/docs"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "kind/refactor"
  color: "cfd3d7"
  description: "Code refactoring"

# priority
- name: "priority/critical"
  color: "b60205"
  description: "Must fix ASAP"
- name: "priority/high"
  color: "d93f0b"
  description: "High priority"
- name: "priority/low"
  color: "0e8a16"
  description: "Low priority"

# status
- name: "status/wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "status/stale"
  color: "ededed"
  description: "No activity for a while"

# good for newcomers
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

# area
- name: "area/ci"
  color: "c5def5"
  description: "CI/CD, GitHub Actions, Tools"
- name: "area/core"
  color: "bfdadc"
  description: "Source code changes"
- name: "area/tests"
  color: "c2e0c6"
  description: "Tests and coverage"
